baseURL = "https://davidannebicque.fr"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "David Annebicque"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    cours = "cours"
    recherche = "recherche"
    projet = "projet"
